Added images with titles
SergiyKozachok/angularHomeWorks pull request #1
Opened 2018-09-17 12:46 UTC by SergiyKozachok

Added gallery of images

2018-09-17 21:45 UTC, yurykozhenov requested changes

2018-09-17 21:45 UTC, yurykozhenov commented on package.json
> +    "@angular/animations": "github:angular/animations-builds",
Рекомендую просто вказати версію (`^6.0.3`) 
Посилатись на репозиторій з білдами погана практика, оскільки якщо там щось оновиться то при переустановці npm модулів проект може зламатись

2018-09-17 21:45 UTC, yurykozhenov commented on package.json
> +    "@angular/flex-layout": "github:angular/flex-layout-builds",
Остання версія - `6.0.0-beta.17`

2018-09-17 21:45 UTC, yurykozhenov commented on package.json
> +    "@angular/cdk": "github:angular/cdk-builds",
Остання версія - `6.4.7`

2018-09-17 21:45 UTC, yurykozhenov commented on package.json
> +    "@angular/material": "github:angular/material2-builds",
Остання версія - `6.4.7`

2018-09-17 21:45 UTC, yurykozhenov commented on src/app/app.component.html
> +      <img mat-card-image src="{{image.url}}">
Згідно рекомендацій розробників ангуляра, краще писати [src]="item.url". Подвійні фігурні дужки краще використовувати тільки при інтерполяції тексту всередину хтмл контенту, а для атрибутів використовувати квадратні дужки. Це загальна рекомендація, щоб не було плутанини + так виходить трішки компактніше.

2018-09-17 21:45 UTC, yurykozhenov commented on src/index.html
> +  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
Повторний імпорт матеріал іконок (був на 4 лінії)

2018-09-17 21:45 UTC, yurykozhenov commented on src/app/app.component.ts
> +  images  = [
Не обов'язково, але можна тут явно вказати тип змінної (у вигляді кастомно створенного інтерфейса)

2018-09-17 21:45 UTC, yurykozhenov commented on src/index.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Не рекомендую використовувати одночасно дві великі візуальні бібліотеки (Materialize і Angular Material) в проект, бо це сильно збільшує розмір збілдженого проекту і підтормажує сайт. Тут або використовувати одну бібліотеку, або іншу, але не обидві.
І, якщо замість Angular Material вирішиш використовувати Materialize, то краще ставити її як npm модуль, а не використовувати з cdn. Так буде більше контроля над версією бібліотеки і весь цсс буде збиратссь разом, в одному вебпак бандлі.

2018-09-18 11:06 UTC, yurykozhenov requested changes

2018-09-18 11:06 UTC, yurykozhenov commented on package.json
> +    "@angular/flex-layout": "^6.0.3-beta.17",
Зміни на `^6.0.0-beta.18`, бо шось з теперішньою версією проект не запускається

2018-09-18 11:06 UTC, yurykozhenov commented on src/app/app.component.ts
> +  [index: number]: {id: number; title: string; url: string};
Краще зробити тут інтерфейс не із масива, а просто із одного об'єкта (без `[index: number]`). Так можна буде перевикористати цей інтерфейс для одного елемента, у разі необхідності

2018-09-18 11:06 UTC, yurykozhenov commented on src/app/app.component.ts
> +  images: IImages  = [
Якщо зміниш інтерфейс на звичайний об'єкт, то тут буде `IImage[]`

2018-09-18 11:06 UTC, yurykozhenov commented on src/styles.css
> +@import "~@angular/material/prebuilt-themes/indigo-pink.css";
Цей імпорт можна прибрати, оскільки цей цсс файл уже втягується в проект завдяки тому, що ти вказав його в `styles` в `angular.json`

2018-09-18 12:48 UTC, SergiyKozachok commented on package.json
> +    "@angular/flex-layout": "^6.0.3-beta.17",
З цією версією теж проблеми. Почитав оце https://github.com/angular/flex-layout/issues/827 Зараз у них якісь проблеми з сумісністю, всі відкочуються до якихось старіших версій поки що. В мене такої необхідності зараз немає ніби, якось і не використав його. В мене білдиться і стартую якщо не імпортую цей флекс

2018-09-18 13:44 UTC, yurykozhenov commented on package.json
> +    "@angular/flex-layout": "^6.0.3-beta.17",
Якщо будуть трабли то зміниш в цьому ж файлі `"rxjs": "^6.3.2",` на `"rxjs": "^6.2.2",` і запустиш `npm install`

2018-09-18 16:13 UTC, merged